stages:
  - build
  - test

build:
  stage: build
  script:
    -   cd dental-clinic
    -  ./gradlew build -x test 
    -  ./gradlew.bat --stop

test:
  stage: test
  script:
    -   cd dental-clinic
    -  ./gradlew test 
    -  ./gradlew.bat --stop



    
